several_confs:
  - run_dir: ${general.run_dir}
    cwola_path: ${general.run_dir}/cwola/
    cwola_eval_path: ${general.run_dir}/plots/cwola_3000_eval/
    datasets:
      datasr: ${data.cwola.datasr_3000}
      extra_signal: ${data.cwola.extra_signal_3000}
      template:
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: ${general.run_dir}/template/outputs/template_sample3000.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "template"
            new_df_dict: {"template": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "template"
            column_name: "is_signal"
            column_values: -1
      extra_bkg: ${data.cwola.extra_bkg_3000}
    input_path: /srv/beegfs/scratch/users/l/leighm/linearresults/
    cwola_subfolders: window_3100_3300__3700_3900/dope_3000/
    mode: standard
    num_signal: 3000
    sideband_1: "3100_3300"
    sideband_2: "3700_3900"
    num_folds: 5
    max_iter: 250
    early_stopping: 1
    validation_fraction: 0.1
    class_weight: balanced
    num_ensemble: 5
    seeds: [0]
    extra_bkg: 1

  - run_dir: ${general.run_dir}
    cwola_path: ${general.run_dir}/cwola_latent/
    cwola_eval_path: ${general.run_dir}/plots/cwola_latent_3000_eval/
    datasets:
      datasr: ${data.cwola.dataSR_latent_3000}
      extra_signal: ${data.cwola.data_extra_sig_latent_3000}
      plotting_path: ${general.run_dir}/plots/input/cwola/template/
      template: ${data.cwola.dataSB_latent_3000}
      extra_bkg: ${data.cwola.data_extra_bkg_latent_3000}
    input_path: /srv/beegfs/scratch/users/l/leighm/linearresults/
    cwola_subfolders: window_3100_3300__3700_3900/dope_3000/
    mode: standard
    num_signal: 3000
    sideband_1: "3100_3300"
    sideband_2: "3700_3900"
    num_folds: 5
    max_iter: 250
    early_stopping: 1
    validation_fraction: 0.1
    class_weight: balanced
    num_ensemble: 5
    seeds: [0, 1]
    extra_bkg: 1

